# This is a basic workflow to help you get started with Actions

name: pullrepo

# Controls when the workflow will run
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron:  '30 5,17 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Get Repo
        run: git clone https://gitlab.com/lax1dude/eaglercraftx-1.8.git
      - uses: stefanzweifel/git-auto-commit-action@v4
